# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vineitem',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vineitem',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vineitem',
            name='color',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='vineitem',
            name='company',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vineitem',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vineitem',
            name='picture',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='vineitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vineitem',
            name='tags',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vineitem',
            name='type_wine',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='vineitem',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vineitem',
            name='inStock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vineitem',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
