# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vine', '0003_remove_vineitem_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vineitem',
            name='id',
        ),
        migrations.AddField(
            model_name='vineitem',
            name='index',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
